name: task_at_second_november
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # UI
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  fluttertoast: ^8.0.9

  # Services
  json_serializable: ^6.4.1

  #file download packs
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  open_file_safe: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:
  uses-material-design: true